"""baseline schema

Revision ID: 29514a4b85ec
Revises: 
Create Date: 2026-09-11 04:35:42.513152
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name='uq_app_user_username')
    )
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('circle', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday')),
    sa.UniqueConstraint('holiday_date', 'circle', name='uq_holiday_holiday_date_circle')
    )
    op.create_index('ix_holiday_holiday_date', 'holiday', ['holiday_date'], unique=False)
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme')),
    sa.UniqueConstraint('name', name='uq_programme_name')
    )
    op.create_table('reporting_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight BETWEEN 0 AND 100', name=op.f('ck_reporting_stage_weight_is_percentage')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporting_stage')),
    sa.UniqueConstraint('name', name='uq_reporting_stage_name'),
    sa.UniqueConstraint('sequence_position', name='uq_reporting_stage_sequence_position')
    )
    op.create_table('scheduling_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_task_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('partition_by', sa.String(length=20), server_default='global', nullable=False),
    sa.Column('count_distinct_by', sa.String(length=20), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('window_working_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('pool_key', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type IN ('starts_per_day','concurrent','distinct_in_window')", name=op.f('ck_scheduling_constraint_rule_type_known')),
    sa.CheckConstraint('max_count >= 1', name=op.f('ck_scheduling_constraint_max_count_positive')),
    sa.CheckConstraint('window_working_days >= 1', name=op.f('ck_scheduling_constraint_window_at_least_one_day')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_constraint')),
    sa.UniqueConstraint('template_task_number', 'rule_type', 'partition_by', name='uq_scheduling_constraint_task_rule_partition')
    )
    op.create_index('ix_scheduling_constraint_template_task_number', 'scheduling_constraint', ['template_task_number'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=150), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_project_id_created_at', 'audit_log', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_scope_id', 'audit_log', ['scope_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Not Started', nullable=False),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('baseline_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('baseline_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_project_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('programme_id', 'name', name='uq_project_programme_id_name')
    )
    op.create_index('ix_project_programme_id', 'project', ['programme_id'], unique=False)
    op.create_table('task_stage_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_task_number', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['reporting_stage.id'], name=op.f('fk_task_stage_map_stage_id_reporting_stage'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stage_map')),
    sa.UniqueConstraint('template_task_number', name='uq_task_stage_map_template_task_number')
    )
    op.create_index('ix_task_stage_map_stage_id', 'task_stage_map', ['stage_id'], unique=False)
    op.create_table('execution_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('circle', sa.String(length=20), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('template_task_number', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('baseline_version', sa.Integer(), nullable=False),
    sa.Column('baseline_planned_start', sa.Date(), nullable=True),
    sa.Column('baseline_planned_finish', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_by', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_execution_archive_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_archive'))
    )
    op.create_index('ix_execution_archive_project_id_baseline_version', 'execution_archive', ['project_id', 'baseline_version'], unique=False)
    op.create_index('ix_execution_archive_scope_id', 'execution_archive', ['scope_id'], unique=False)
    op.create_table('leadership_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('circle', sa.String(length=20), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('risk_area', sa.String(length=120), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='Medium', nullable=False),
    sa.Column('priority_sort', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Open', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_leadership_action_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leadership_action'))
    )
    op.create_index('ix_leadership_action_project_id', 'leadership_action', ['project_id'], unique=False)
    op.create_index('ix_leadership_action_project_id_priority_sort', 'leadership_action', ['project_id', 'priority_sort'], unique=False)
    op.create_table('project_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_assignment_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_project_assignment_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_assignment')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_assignment_project_id_user_id')
    )
    op.create_index('ix_project_assignment_user_id', 'project_assignment', ['user_id'], unique=False)
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('circle', sa.String(length=20), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('num_servers', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='Not Started', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_servers >= 0', name=op.f('ck_scope_num_servers_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_scope_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope')),
    sa.UniqueConstraint('project_id', 'node_id', name='uq_scope_project_id_node_id')
    )
    op.create_index('ix_scope_circle', 'scope', ['circle'], unique=False)
    op.create_index('ix_scope_project_id', 'scope', ['project_id'], unique=False)
    op.create_index('ix_scope_project_id_circle', 'scope', ['project_id', 'circle'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('template_task_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('predecessor_template_number', sa.Integer(), nullable=True),
    sa.Column('is_prerequisite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('owner_role', sa.String(length=100), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_days >= 0', name=op.f('ck_task_duration_non_negative')),
    sa.CheckConstraint('planned_finish IS NULL OR planned_start IS NULL OR planned_finish >= planned_start', name=op.f('ck_task_planned_finish_after_start')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id'], name=op.f('fk_task_scope_id_scope'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    sa.UniqueConstraint('scope_id', 'template_task_number', name='uq_task_scope_id_template_task_number')
    )
    op.create_index('ix_task_project_id', 'task', ['project_id'], unique=False)
    op.create_index('ix_task_project_id_template_task_number', 'task', ['project_id', 'template_task_number'], unique=False)
    op.create_index('ix_task_scope_id', 'task', ['scope_id'], unique=False)
    op.create_table('task_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Not Started', nullable=False),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('delay_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'Completed') OR (actual_start IS NOT NULL AND actual_finish IS NOT NULL)", name=op.f('ck_task_execution_completed_requires_both_dates')),
    sa.CheckConstraint("(status <> 'In Progress') OR (actual_start IS NOT NULL)", name=op.f('ck_task_execution_in_progress_requires_start')),
    sa.CheckConstraint("(status <> 'Not Started') OR (actual_start IS NULL AND actual_finish IS NULL)", name=op.f('ck_task_execution_not_started_has_no_dates')),
    sa.CheckConstraint('actual_finish IS NULL OR actual_finish >= actual_start', name=op.f('ck_task_execution_finish_after_start')),
    sa.CheckConstraint('actual_finish IS NULL OR actual_start IS NOT NULL', name=op.f('ck_task_execution_finish_requires_start')),
    sa.CheckConstraint('delay_days >= 0', name=op.f('ck_task_execution_delay_days_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_execution_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id'], name=op.f('fk_task_execution_scope_id_scope'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_execution_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_execution')),
    sa.UniqueConstraint('scope_id', 'task_id', name='uq_task_execution_scope_id_task_id')
    )
    op.create_index('ix_task_execution_project_id', 'task_execution', ['project_id'], unique=False)
    op.create_index('ix_task_execution_project_id_status', 'task_execution', ['project_id', 'status'], unique=False)
    op.create_index('ix_task_execution_scope_id', 'task_execution', ['scope_id'], unique=False)
    op.create_index('ix_task_execution_task_id', 'task_execution', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_execution_task_id', table_name='task_execution')
    op.drop_index('ix_task_execution_scope_id', table_name='task_execution')
    op.drop_index('ix_task_execution_project_id_status', table_name='task_execution')
    op.drop_index('ix_task_execution_project_id', table_name='task_execution')
    op.drop_table('task_execution')
    op.drop_index('ix_task_scope_id', table_name='task')
    op.drop_index('ix_task_project_id_template_task_number', table_name='task')
    op.drop_index('ix_task_project_id', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_scope_project_id_circle', table_name='scope')
    op.drop_index('ix_scope_project_id', table_name='scope')
    op.drop_index('ix_scope_circle', table_name='scope')
    op.drop_table('scope')
    op.drop_index('ix_project_assignment_user_id', table_name='project_assignment')
    op.drop_table('project_assignment')
    op.drop_index('ix_leadership_action_project_id_priority_sort', table_name='leadership_action')
    op.drop_index('ix_leadership_action_project_id', table_name='leadership_action')
    op.drop_table('leadership_action')
    op.drop_index('ix_execution_archive_scope_id', table_name='execution_archive')
    op.drop_index('ix_execution_archive_project_id_baseline_version', table_name='execution_archive')
    op.drop_table('execution_archive')
    op.drop_index('ix_task_stage_map_stage_id', table_name='task_stage_map')
    op.drop_table('task_stage_map')
    op.drop_index('ix_project_programme_id', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_audit_log_scope_id', table_name='audit_log')
    op.drop_index('ix_audit_log_project_id_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_scheduling_constraint_template_task_number', table_name='scheduling_constraint')
    op.drop_table('scheduling_constraint')
    op.drop_table('reporting_stage')
    op.drop_table('programme')
    op.drop_index('ix_holiday_holiday_date', table_name='holiday')
    op.drop_table('holiday')
    op.drop_table('app_user')
    # ### end Alembic commands ###
