apiVersion: v1
kind: Service
metadata:
  name: iptt-web
  labels:
    app.kubernetes.io/name: iptt
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: iptt
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
