apiVersion: v1
kind: Service
metadata:
  name: iptt-api
  labels:
    app.kubernetes.io/name: iptt
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: iptt
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
